export { HeroSection } from "./HeroSection";
export { TrustSection } from "./TrustSection";
export { FeaturedProducts } from "./FeaturedProducts";
export { WhyBestSection } from "./WhyBestSection";
export { ProductShowcase } from "./ProductShowcase";
export { ShopByCategory } from "./ShopByCategory";
export { BlogSection } from "./BlogSection";
export { InstagramSection } from "./InstagramSection";
export { TestimonialsSection } from "./TestimonialsSection";
